language: node_js
node_js:
  - 15.12.0
cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  cleanup: false
  github-token: $GITHUB_TOKEN
  on:
    branch: master