# Title

version: '3.8'

networks:
  default:
    name: CondGoods-Network

services:

  spark-tls-ca:
    image: hyperledger/fabric-ca:latest
    container_name: Spark-TLS-CA
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/Spark-TLS-CA
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=Spark-TLS-CA
      # Line 274 till 281 needs to be removed (remove profile) in fabric-ca-server-config.yaml
      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9444
    ports:
      - "7054:7054"
    volumes:
      - "~/container-volumes/Spark-TLS-CA:/etc/hyperledger/Spark-TLS-CA"
    command: sh -c 'fabric-ca-server start -b tls-admin:tls-Welkom01!'



  spark-ca:
    image: hyperledger/fabric-ca:latest
    container_name: Spark-CA
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/Spark-CA
      - FABRIC_CA_SERVER_PORT=7055
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=tls/cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=tls/key.pem
      - FABRIC_CA_SERVER_CA_NAME=Spark-CA
      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9444
    ports:
      - "7055:7055"
    volumes:
      - "~/container-volumes/Spark-CA:/etc/hyperledger/Spark-CA"
    command: sh -c 'fabric-ca-server start -b rca-admin:rca-Welkom01!'



  spark-int-ca:
    image: hyperledger/fabric-ca:latest
    container_name: Spark-INT-CA
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/Spark-INT-CA
      - FABRIC_CA_SERVER_PORT=7056
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=tls/cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=tls/key.pem
      - FABRIC_CA_SERVER_CA_NAME=Spark-INT-CA
      - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_CACONSTRAINT_MAXPATHLEN=0
      - FABRIC_CA_SERVER_CSR_CN=
      - FABRIC_CA_SERVER_CSR_CA_PATHLENGTH=0
      - FABRIC_CA_SERVER_INTERMEDIATE_PARENTSERVER_URL=https://rca-admin:'rca-Welkom01!'@localhost:7055
      - FABRIC_CA_SERVER_INTERMEDIATE_PARENTSERVER_CANAME=Spark-CA
      - FABRIC_CA_SERVER_INTERMEDIATE_ENROLLMENT_HOSTS=localhost
      - FABRIC_CA_SERVER_INTERMEDIATE_ENROLLMENT_PROFILE=ca
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=tls/tls-ca-cert.pem
      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9445
    ports:
      - "7056:7056"
    volumes:
      - "~/container-volumes/Spark-INT-CA:/etc/hyperledger/Spark-INT-CA"
    command: /bin/bash -c '/etc/hyperledger/Spark-INT-CA/start-int-ca.sh'



  peer0-couchdb:
      image: couchdb:latest
      container_name: peer0-couchdb
      environment:
        - COUCHDB_USER=peer0-couchdb-admin
        - COUCHDB_PASSWORD=peer0-couchdb-Welkom01!
      ports:
        - "5984:5984"
      networks:
        - CondGoods-Network


  peer0-spark:
    image: hyperledger/fabric-peer:2.3
    container_name: peer0-spark
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_ID=peer0-spark
      - CORE_PEER_NETWORKID=test
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
      - CORE_PEER_CHAINCODEADDRESS=localhost:7062
      - CORE_PEER_ADDRESS=localhost:7061
      - CORE_PEER_MSPCONFIGPATH=msp
      - CORE_PEER_LOCALMSPID=spark
      - CORE_PEER_FILESYSTEMPATH=/var/hyperledger/production
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:7071
      - CORE_PEER_GOSSIP_ENDPOINT=localhost:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=localhost:7061
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=tls/tls-ca-cert.pem
      - CORE_PEER_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_PEER_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-couchdb:5984
      - CORE_PEER_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0-couchdb-admin
      - CORE_PEER_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=peer0-couchdb-Welkom01!
      - CORE_PEER_LEDGER_SNAPSHOTS=var/hyperledger/production/snapshots
      #- CORE_PEER_OPERATIONS_LISTENADDRESS=127.0.0.1:9443
      #- CORE_PEER_OPERATIONS_TLS_ENABLED=true
      #- CORE_PEER_OPERATIONS_TLS_CERT_FILE=
      #- CORE_PEER_OPERATIONS_TLS_KEY_FILE=
      #- CORE_PEER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_METRICS_PROVIDER=disabled
      #- CORE_PEER_METRICS_STATSD_ADDRESS=127.0.0.1:8125
      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9444
    ports:
      - "7061:7061"
      - "7062:7062"
      - "7071:7071"
    volumes:
      - "~/container-volumes/peer0-spark/production:/var/hyperledger/production"
      - "~/organizations/peerOrganizations/spark/peers/peer0-spark/msp:/etc/hyperledger/fabric/msp"
      - "~/organizations/peerOrganizations/spark/peers/peer0-spark/tls:/etc/hyperledger/fabric/tls"
    #depends_on:
      #- peer0-couchdb
    command: peer node start


version: '3.8'

networks:
  default:
    name: CondGoods-Network

services:

  peer1-couchdb:
      image: couchdb:latest
      container_name: peer1-couchdb
      environment:
        - COUCHDB_USER=peer1-couchdb-admin
        - COUCHDB_PASSWORD=peer1-couchdb-Welkom01!
      ports:
        - "5985:5985"


  peer1-spark:
    image: hyperledger/fabric-peer:2.3
    container_name: peer1-spark
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_ID=peer1-spark
      - CORE_PEER_NETWORKID=test
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7081
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7082
      - CORE_PEER_CHAINCODEADDRESS=localhost:7082
      - CORE_PEER_ADDRESS=172.22.0.5:7081
      - CORE_PEER_MSPCONFIGPATH=msp
      - CORE_PEER_LOCALMSPID=spark
      - CORE_PEER_FILESYSTEMPATH=/var/hyperledger/production
      - CORE_PEER_GOSSIP_BOOTSTRAP=172.22.0.5:7061
      - CORE_PEER_GOSSIP_ENDPOINT=172.22.0.6.:7081
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=localhost:7081
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=tls/tls-ca-cert.pem
      - CORE_PEER_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_PEER_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-couchdb:5985
      - CORE_PEER_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1-couchdb-admin
      - CORE_PEER_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=peer1-couchdb-Welkom01!
      - CORE_PEER_LEDGER_SNAPSHOTS=var/hyperledger/production/snapshots
      #- CORE_PEER_OPERATIONS_LISTENADDRESS=127.0.0.1:9443
      #- CORE_PEER_OPERATIONS_TLS_ENABLED=true
      #- CORE_PEER_OPERATIONS_TLS_CERT_FILE=
      #- CORE_PEER_OPERATIONS_TLS_KEY_FILE=
      #- CORE_PEER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_METRICS_PROVIDER=disabled
      #- CORE_PEER_METRICS_STATSD_ADDRESS=127.0.0.1:8125
      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9444
    ports:
      - "7081:7081"
      - "7082:7082"
    volumes:
      - "~/container-volumes/peer1-spark/production:/var/hyperledger/production"
      - "~/organizations/peerOrganizations/spark/peers/peer1-spark/msp:/etc/hyperledger/fabric/msp"
      - "~/organizations/peerOrganizations/spark/peers/peer1-spark/tls:/etc/hyperledger/fabric/tls"
    #depends_on:
      #- peer0-couchdb
    command: peer node start


  orderer0-spark:
    image: hyperledger/fabric-orderer:2.3
    container_name: orderer0-spark
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_GENERAL_LISTENADDRESS=127.0.0.1
      - ORDERER_GENERAL_LISTENPORT=7040
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=tls/key.pem
      - ORDERER_GENERAL_TLS_CERTIFICATE=tls/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=tls/tls-ca-cert.pem
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=tls/tls-ca-cert.pem
      # KEEPALIVE SETTINGS SHOULD NOT BE OVERRIDDEN
      - ORDERER_GENERAL_KEEPALIVE_SERVERMININTERVAL=60s
      - ORDERER_GENERAL_KEEPALIVE_SERVERINTERVAL=7200s
      - ORDERER_GENERAL_KEEPALIVE_SERVERTIMEOUT=20s
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=tls/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=tls/key.pem
      # CLUSTER SETTINGS NEED TO BE SET TOGETHER
      #- ORDERER_GENERAL_CLUSTER_LISTENPORT=
      #- ORDERER_GENERAL_CLUSTER_LISTENADDRESS=
      #- ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=
      #- ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPDIR=msp
      - ORDERER_GENERAL_LOCALMSPID=spark
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer
      #- ORDERER_OPERATIONS_LISTENADDRESS=127.0.0.1:8443
      #- ORDERER_OPERATIONS_TLS_ENABLED=true
      #- ORDERER_OPERATIONS_TLS_CERTIFICATE=tls/cert.pem
      #- ORDERER_OPERATIONS_TLS_PRIVATEKEY=tls/key.pem
      #- ORDERER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      #- ORDERER_OPERATIONS_TLS_CLIENTROOTCAS=tls/tls-ca-root.pem
      #- ORDERER_METRICS_PROVIDER=disabled
      #- ORDERER_METRICS_STATSD_ADDRESS=127.0.0.1:8125
      - ORDERER_ADMIN_LISTENADDRESS=127.0.0.1:9440
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/etc/hyperledger/fabric/tls/cert.pem
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/etc/hyperledger/fabric/tls/key.pem
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      #- ORDERER_CHANNELPARTICIPATION_MAXREQUESTBODYSIZE=1 MB
      - ORDERER_CONSENSUS_WALDIR=/var/hyperledger/production/orderer/etcdraft/wal
      - ORDERER_CONSENSUS_SNAPDIR=/var/hyperledger/production/orderer/etcdraft/snapshot

    ports:
      - "7040:7040"
      - "9440:9440"
    volumes:
      - "~/container-volumes/orderer0-spark/production:/var/hyperledger/production"
      - "~/organizations/ordererOrganizations/spark/orderers/orderer0-spark/msp:/etc/hyperledger/fabric/msp"
      - "~/organizations/ordererOrganizations/spark/orderers/orderer0-spark/tls:/etc/hyperledger/fabric/tls"
    command: orderer start