# Docker-compose file for the TLS-CA and Organization-CA (fe: spark-TLS-CA, spark-CA)

version: '3.8'

networks:
  default:
    name: CondGoods-Network

services:

  spark-tls-ca:
    image: hyperledger/fabric-ca:latest
    container_name: Spark-TLS-CA
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/Spark-TLS-CA
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=Spark-TLS-CA
      # Line 274 till 281 needs to be removed (remove profile) in fabric-ca-server-config.yaml
      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9444
    ports:
      - "7054:7054"
    volumes:
      - "~/container-volumes/Spark-TLS-CA:/etc/hyperledger/Spark-TLS-CA"
    command: sh -c 'fabric-ca-server start -b tls-admin:tls-Welkom01!'



  spark-ca:
    image: hyperledger/fabric-ca:latest
    container_name: Spark-CA
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/Spark-CA
      - FABRIC_CA_SERVER_PORT=7055
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=tls/cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=tls/key.pem
      - FABRIC_CA_SERVER_CA_NAME=Spark-CA
      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9444
    ports:
      - "7055:7055"
    volumes:
      - "~/container-volumes/Spark-CA:/etc/hyperledger/Spark-CA"
    command: sh -c 'fabric-ca-server start -b rca-admin:rca-Welkom01!'



#  spark-int-ca:
#    image: hyperledger/fabric-ca:latest
#    container_name: Spark-INT-CA
#    environment:
#      - FABRIC_CA_HOME=/etc/hyperledger/Spark-INT-CA
#      - FABRIC_CA_SERVER_PORT=7056
#      - FABRIC_CA_SERVER_TLS_ENABLED=true
#      - FABRIC_CA_SERVER_TLS_CERTFILE=tls/cert.pem
#      - FABRIC_CA_SERVER_TLS_KEYFILE=tls/key.pem
#      - FABRIC_CA_SERVER_CA_NAME=Spark-INT-CA
#      - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_CACONSTRAINT_MAXPATHLEN=0
#      - FABRIC_CA_SERVER_CSR_CN=
#      - FABRIC_CA_SERVER_CSR_CA_PATHLENGTH=0
#      - FABRIC_CA_SERVER_INTERMEDIATE_PARENTSERVER_URL=https://rca-admin:'rca-Welkom01!'@localhost:7055
#      - FABRIC_CA_SERVER_INTERMEDIATE_PARENTSERVER_CANAME=Spark-CA
#      - FABRIC_CA_SERVER_INTERMEDIATE_ENROLLMENT_HOSTS=localhost
#      - FABRIC_CA_SERVER_INTERMEDIATE_ENROLLMENT_PROFILE=ca
#      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=tls/tls-ca-cert.pem
#      #- FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=127.0.0.1:9445
#    ports:
#      - "7056:7056"
#    volumes:
#      - "~/container-volumes/Spark-INT-CA:/etc/hyperledger/Spark-INT-CA"
#    command: /bin/bash -c '/etc/hyperledger/Spark-INT-CA/start-int-ca.sh'